sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: liu@gmail@123
  alioss:
    endpoint: null
    access-key-id: null
    access-key-secret: null
    bucket-name: null
  localfile:
    root: "/Users/liujiaming/Documents/WorkSpace/temp/"
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: "wx4118f764d220411c"
    secret: "41be009eece917ec28b00f0533b6e8f4"